#!/usr/bin/env bash
# Script that displays a list of currently running processes in a user-oriented format showing process hierarchy

ps -eo user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command --forest
