#!/usr/bin/env bash
# shellcheck disable=SC2009

# Get the PID of the 4-to_infinity_and_beyond process
pid=$(ps aux | grep "[4]-to_infinity_and_beyond" | awk '{print $2}')

# Kill the process if found
if [ -n "$pid" ]; then
    kill "$pid"
fi
